apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ballot
  namespace: vivekklpkb-ballot-pr-open-39
spec:
  ingressClassName: nginx 
  rules:
  - host: "vivekklpkb-ballot-pr-open-39.ballot.3.6.93.68.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ballot
            port:
              number: 80
